### ISSUE TITLE
Compat hasmethod for older Julia?

### ISSUE THREAD

**Issue by aminya** [oxinabox/Tricks.jl#18]
If I want to use Tricks in my package, I should do a lot of hackeries to only load Tricks if VERSION is above 1.3 and then do something like following to make sure that this works across all the versions.

Isn't it better to relax the compat bound of Julia in Tricks and define the following for compatibility?
```jl
@static if VERSION < v"1.3"
    static_hasmethod(args...) = hasmethod(args...)
end
```

This way I can just use Tricks without any concerns.

**Comment by oxinabox** [comment]
I don't think I agree.
because the difference is very significant.
It is between zero run time cost and fairly substantial run-time cost


Potentially a method could be added:
```
 @static if VERSION < v"1.3"
    const compat_hasmethod = hasmethod
else
    const compat_hasmethod = static_hasmethod
end
```

then one can use `compat_hasmethod` knowing that it varies depending on release.
and we could relax the constraints in this package.

But i think making it called `static_hasmethod` when it might not be static is probably not a good thing to do.

**Comment by aminya** [comment]
Yes, the name of the function is not an issue.  That `compat_hasmethod` is a good idea!

**Comment by aminya** [comment]
@oxinabox Any update on this?
